"""Canonical spell-to-class associations from SRD 5.1 PDF pages 105-113.

SOURCE: SRD_CC_v5.1.pdf pages 105-113 "Spell Lists"
EXTRACTION: PDF text is corrupted; manually mapped via visual inspection
PROVENANCE: Each class section extracted from designated pages
"""

from typing import Final

# Spell simple_names organized by class
# Each list is alphabetically sorted for maintainability
# Classes are in alphabetical order

BARD_SPELLS: Final[list[str]] = [
    # Cantrips
    "dancing_lights",
    "light",
    "mage_hand",
    "mending",
    "message",
    "minor_illusion",
    "prestidigitation",
    "true_strike",
    "vicious_mockery",
    # 1st Level
    "animal_friendship",
    "bane",
    "charm_person",
    "comprehend_languages",
    "cure_wounds",
    "detect_magic",
    "disguise_self",
    "faerie_fire",
    "feather_fall",
    "healing_word",
    "heroism",
    "hideous_laughter",
    "identify",
    "illusory_script",
    "longstrider",
    "silent_image",
    "sleep",
    "speak_with_animals",
    "thunderwave",
    "unseen_servant",
    # 2nd Level
    "animal_messenger",
    "blindnessdeafness",
    "calm_emotions",
    "detect_thoughts",
    "enhance_ability",
    "enthrall",
    "heat_metal",
    "hold_person",
    "invisibility",
    "knock",
    "lesser_restoration",
    "locate_animals_or_plants",
    "locate_object",
    "magic_mouth",
    "see_invisibility",
    "shatter",
    "silence",
    "suggestion",
    "zone_of_truth",
    # 3rd Level
    "bestow_curse",
    "clairvoyance",
    "dispel_magic",
    "fear",
    "glyph_of_warding",
    "hypnotic_pattern",
    "major_image",
    "nondetection",
    "plant_growth",
    "sending",
    "speak_with_dead",
    "speak_with_plants",
    "stinking_cloud",
    "tiny_hut",
    "tongues",
    # 4th Level
    "compulsion",
    "confusion",
    "dimension_door",
    "freedom_of_movement",
    "greater_invisibility",
    "hallucinatory_terrain",
    "locate_creature",
    "polymorph",
    # 5th Level
    "animate_objects",
    "awaken",
    "dominate_person",
    "dream",
    "geas",
    "greater_restoration",
    "hold_monster",
    "legend_lore",
    "mass_cure_wounds",
    "mislead",
    "modify_memory",
    "planar_binding",
    "raise_dead",
    "scrying",
    "seeming",
    "teleportation_circle",
    # 6th Level
    "eyebite",
    "find_the_path",
    "guards_and_wards",
    "irresistible_dance",
    "mass_suggestion",
    "programmed_illusion",
    "true_seeing",
    # 7th Level
    "arcane_sword",
    "etherealness",
    "forcecage",
    "magnificent_mansion",
    "mirage_arcane",
    "project_image",
    "regenerate",
    "resurrection",
    "symbol",
    "teleport",
    # 8th Level
    "dominate_monster",
    "feeblemind",
    "glibness",
    "mind_blank",
    "power_word_stun",
    # 9th Level
    "foresight",
    "power_word_kill",
    "true_polymorph",
]

CLERIC_SPELLS: Final[list[str]] = [
    # Cantrips
    "guidance",
    "light",
    "mending",
    "resistance",
    "sacred_flame",
    "spare_the_dying",
    "thaumaturgy",
    # 1st Level
    "bane",
    "bless",
    "command",
    "create_or_destroy_water",
    "cure_wounds",
    "detect_evil_and_good",
    "detect_magic",
    "detect_poison_and_disease",
    "guiding_bolt",
    "healing_word",
    "inflict_wounds",
    "protection_from_evil_and_good",
    "purify_food_and_drink",
    "sanctuary",
    "shield_of_faith",
    # 2nd Level
    "aid",
    "augury",
    "blindnessdeafness",
    "calm_emotions",
    "continual_flame",
    "enhance_ability",
    "find_traps",
    "gentle_repose",
    "hold_person",
    "lesser_restoration",
    "locate_object",
    "prayer_of_healing",
    "protection_from_poison",
    "silence",
    "spiritual_weapon",
    "warding_bond",
    "zone_of_truth",
    # 3rd Level
    "animate_dead",
    "beacon_of_hope",
    "bestow_curse",
    "clairvoyance",
    "create_food_and_water",
    "daylight",
    "dispel_magic",
    "glyph_of_warding",
    "magic_circle",
    "mass_healing_word",
    "meld_into_stone",
    "protection_from_energy",
    "remove_curse",
    "revivify",
    "sending",
    "speak_with_dead",
    "spirit_guardians",
    "tongues",
    "water_walk",
    # 4th Level
    "banishment",
    "control_water",
    "death_ward",
    "divination",
    "freedom_of_movement",
    "guardian_of_faith",
    "locate_creature",
    "stone_shape",
    # 5th Level
    "commune",
    "contagion",
    "dispel_evil_and_good",
    "flame_strike",
    "geas",
    "greater_restoration",
    "hallow",
    "insect_plague",
    "legend_lore",
    "mass_cure_wounds",
    "planar_binding",
    "raise_dead",
    "scrying",
    # 6th Level
    "blade_barrier",
    "create_undead",
    "find_the_path",
    "forbiddance",
    "harm",
    "heal",
    "heroes_feast",
    "planar_ally",
    "true_seeing",
    "word_of_recall",
    # 7th Level
    "conjure_celestial",
    "divine_word",
    "etherealness",
    "fire_storm",
    "plane_shift",
    "regenerate",
    "resurrection",
    "symbol",
    # 8th Level
    "antimagic_field",
    "control_weather",
    "earthquake",
    "holy_aura",
    # 9th Level
    "astral_projection",
    "gate",
    "mass_heal",
    "true_resurrection",
]

DRUID_SPELLS: Final[list[str]] = [
    # Cantrips
    "druidcraft",
    "guidance",
    "mending",
    "poison_spray",
    "produce_flame",
    "resistance",
    "shillelagh",
    # 1st Level
    "animal_friendship",
    "charm_person",
    "create_or_destroy_water",
    "cure_wounds",
    "detect_magic",
    "detect_poison_and_disease",
    "entangle",
    "faerie_fire",
    "fog_cloud",
    "goodberry",
    "healing_word",
    "jump",
    "longstrider",
    "purify_food_and_drink",
    "speak_with_animals",
    "thunderwave",
    # 2nd Level
    "animal_messenger",
    "barkskin",
    "darkvision",
    "enhance_ability",
    "find_traps",
    "flame_blade",
    "flaming_sphere",
    "gust_of_wind",
    "heat_metal",
    "hold_person",
    "lesser_restoration",
    "locate_animals_or_plants",
    "locate_object",
    "moonbeam",
    "pass_without_trace",
    "protection_from_poison",
    "spike_growth",
    # 3rd Level
    "call_lightning",
    "conjure_animals",
    "daylight",
    "dispel_magic",
    "meld_into_stone",
    "plant_growth",
    "protection_from_energy",
    "sleet_storm",
    "speak_with_plants",
    "water_breathing",
    "water_walk",
    "wind_wall",
    # 4th Level
    "blight",
    "confusion",
    "conjure_minor_elementals",
    "conjure_woodland_beings",
    "control_water",
    "dominate_beast",
    "freedom_of_movement",
    "giant_insect",
    "hallucinatory_terrain",
    "ice_storm",
    "locate_creature",
    "polymorph",
    "stone_shape",
    "stoneskin",
    "wall_of_fire",
    # 5th Level
    "antilife_shell",
    "awaken",
    "commune_with_nature",
    "conjure_elemental",
    "contagion",
    "geas",
    "greater_restoration",
    "insect_plague",
    "mass_cure_wounds",
    "planar_binding",
    "reincarnate",
    "scrying",
    "tree_stride",
    "wall_of_stone",
    # 6th Level
    "conjure_fey",
    "find_the_path",
    "heal",
    "heroes_feast",
    "move_earth",
    "sunbeam",
    "transport_via_plants",
    "wall_of_thorns",
    "wind_walk",
    # 7th Level
    "fire_storm",
    "mirage_arcane",
    "plane_shift",
    "regenerate",
    "reverse_gravity",
    # 8th Level
    "animal_shapes",
    "antipathysympathy",
    "control_weather",
    "earthquake",
    "feeblemind",
    "sunburst",
    # 9th Level
    "foresight",
    "shapechange",
    "storm_of_vengeance",
    "true_resurrection",
]

PALADIN_SPELLS: Final[list[str]] = [
    # 1st Level
    "bless",
    "command",
    "cure_wounds",
    "detect_evil_and_good",
    "detect_magic",
    "detect_poison_and_disease",
    "divine_favor",
    "heroism",
    "protection_from_evil_and_good",
    "purify_food_and_drink",
    "shield_of_faith",
    # 2nd Level
    "aid",
    "branding_smite",
    "find_steed",
    "lesser_restoration",
    "locate_object",
    "magic_weapon",
    "protection_from_poison",
    "zone_of_truth",
    # 3rd Level
    "create_food_and_water",
    "daylight",
    "dispel_magic",
    "magic_circle",
    "remove_curse",
    "revivify",
    # 4th Level
    "banishment",
    "death_ward",
    "locate_creature",
    # 5th Level
    "dispel_evil_and_good",
    "geas",
    "raise_dead",
]

RANGER_SPELLS: Final[list[str]] = [
    # 1st Level
    "alarm",
    "animal_friendship",
    "cure_wounds",
    "detect_magic",
    "detect_poison_and_disease",
    "fog_cloud",
    "goodberry",
    "hunters_mark",
    "jump",
    "longstrider",
    "speak_with_animals",
    # 2nd Level
    "animal_messenger",
    "barkskin",
    "darkvision",
    "find_traps",
    "lesser_restoration",
    "locate_animals_or_plants",
    "locate_object",
    "pass_without_trace",
    "protection_from_poison",
    "silence",
    "spike_growth",
    # 3rd Level
    "conjure_animals",
    "daylight",
    "nondetection",
    "plant_growth",
    "protection_from_energy",
    "speak_with_plants",
    "water_breathing",
    "water_walk",
    "wind_wall",
    # 4th Level
    "conjure_woodland_beings",
    "freedom_of_movement",
    "locate_creature",
    "stoneskin",
    # 5th Level
    "commune_with_nature",
    "tree_stride",
]

SORCERER_SPELLS: Final[list[str]] = [
    # Cantrips
    "acid_splash",
    "chill_touch",
    "dancing_lights",
    "fire_bolt",
    "light",
    "mage_hand",
    "mending",
    "message",
    "minor_illusion",
    "poison_spray",
    "prestidigitation",
    "ray_of_frost",
    "shocking_grasp",
    "true_strike",
    # 1st Level
    "burning_hands",
    "charm_person",
    "color_spray",
    "comprehend_languages",
    "detect_magic",
    "disguise_self",
    "expeditious_retreat",
    "false_life",
    "feather_fall",
    "fog_cloud",
    "jump",
    "mage_armor",
    "magic_missile",
    "shield",
    "silent_image",
    "sleep",
    "thunderwave",
    # 2nd Level
    "alter_self",
    "blindnessdeafness",
    "blur",
    "darkness",
    "darkvision",
    "detect_thoughts",
    "enhance_ability",
    "enlargereduce",
    "gust_of_wind",
    "hold_person",
    "invisibility",
    "knock",
    "levitate",
    "mirror_image",
    "misty_step",
    "scorching_ray",
    "see_invisibility",
    "shatter",
    "spider_climb",
    "suggestion",
    "web",
    # 3rd Level
    "blink",
    "clairvoyance",
    "counterspell",
    "daylight",
    "dispel_magic",
    "fear",
    "fireball",
    "fly",
    "gaseous_form",
    "haste",
    "hypnotic_pattern",
    "lightning_bolt",
    "major_image",
    "protection_from_energy",
    "sleet_storm",
    "slow",
    "stinking_cloud",
    "tongues",
    "water_breathing",
    "water_walk",
    # 4th Level
    "banishment",
    "blight",
    "confusion",
    "dimension_door",
    "dominate_beast",
    "greater_invisibility",
    "ice_storm",
    "polymorph",
    "stoneskin",
    "wall_of_fire",
    # 5th Level
    "animate_objects",
    "cloudkill",
    "cone_of_cold",
    "creation",
    "dominate_person",
    "hold_monster",
    "insect_plague",
    "seeming",
    "telekinesis",
    "teleportation_circle",
    "wall_of_stone",
    # 6th Level
    "chain_lightning",
    "circle_of_death",
    "disintegrate",
    "eyebite",
    "globe_of_invulnerability",
    "mass_suggestion",
    "move_earth",
    "sunbeam",
    "true_seeing",
    # 7th Level
    "delayed_blast_fireball",
    "etherealness",
    "finger_of_death",
    "fire_storm",
    "plane_shift",
    "prismatic_spray",
    "reverse_gravity",
    "teleport",
    # 8th Level
    "dominate_monster",
    "earthquake",
    "incendiary_cloud",
    "power_word_stun",
    "sunburst",
    # 9th Level
    "gate",
    "meteor_swarm",
    "power_word_kill",
    "time_stop",
    "wish",
]

WARLOCK_SPELLS: Final[list[str]] = [
    # Cantrips
    "chill_touch",
    "eldritch_blast",
    "mage_hand",
    "minor_illusion",
    "poison_spray",
    "prestidigitation",
    "true_strike",
    # 1st Level
    "charm_person",
    "comprehend_languages",
    "expeditious_retreat",
    "hellish_rebuke",
    "illusory_script",
    "protection_from_evil_and_good",
    "unseen_servant",
    # 2nd Level
    "darkness",
    "enthrall",
    "hold_person",
    "invisibility",
    "mirror_image",
    "misty_step",
    "ray_of_enfeeblement",
    "shatter",
    "spider_climb",
    "suggestion",
    # 3rd Level
    "counterspell",
    "dispel_magic",
    "fear",
    "fly",
    "gaseous_form",
    "hypnotic_pattern",
    "magic_circle",
    "major_image",
    "remove_curse",
    "tongues",
    "vampiric_touch",
    # 4th Level
    "banishment",
    "blight",
    "dimension_door",
    "hallucinatory_terrain",
    # 5th Level
    "contact_other_plane",
    "dream",
    "hold_monster",
    "scrying",
    # 6th Level
    "circle_of_death",
    "conjure_fey",
    "create_undead",
    "eyebite",
    "flesh_to_stone",
    "mass_suggestion",
    "true_seeing",
    # 7th Level
    "etherealness",
    "finger_of_death",
    "forcecage",
    "plane_shift",
    # 8th Level
    "demiplane",
    "dominate_monster",
    "feeblemind",
    "glibness",
    "power_word_stun",
    # 9th Level
    "astral_projection",
    "foresight",
    "imprisonment",
    "power_word_kill",
    "true_polymorph",
]

WIZARD_SPELLS: Final[list[str]] = [
    # Cantrips
    "acid_splash",
    "chill_touch",
    "dancing_lights",
    "fire_bolt",
    "light",
    "mage_hand",
    "mending",
    "message",
    "minor_illusion",
    "poison_spray",
    "prestidigitation",
    "ray_of_frost",
    "shocking_grasp",
    "true_strike",
    # 1st Level
    "alarm",
    "burning_hands",
    "charm_person",
    "color_spray",
    "comprehend_languages",
    "detect_magic",
    "disguise_self",
    "expeditious_retreat",
    "false_life",
    "feather_fall",
    "find_familiar",
    "floating_disk",
    "fog_cloud",
    "grease",
    "hideous_laughter",
    "identify",
    "illusory_script",
    "jump",
    "longstrider",
    "mage_armor",
    "magic_missile",
    "protection_from_evil_and_good",
    "shield",
    "silent_image",
    "sleep",
    "thunderwave",
    "unseen_servant",
    # 2nd Level
    "acid_arrow",
    "alter_self",
    "arcane_lock",
    "arcanists_magic_aura",
    "blindnessdeafness",
    "blur",
    "continual_flame",
    "darkness",
    "darkvision",
    "detect_thoughts",
    "enlargereduce",
    "flaming_sphere",
    "gentle_repose",
    "gust_of_wind",
    "hold_person",
    "invisibility",
    "knock",
    "levitate",
    "locate_object",
    "magic_mouth",
    "magic_weapon",
    "mirror_image",
    "misty_step",
    "ray_of_enfeeblement",
    "rope_trick",
    "scorching_ray",
    "see_invisibility",
    "shatter",
    "spider_climb",
    "suggestion",
    "web",
    # 3rd Level
    "animate_dead",
    "bestow_curse",
    "blink",
    "clairvoyance",
    "counterspell",
    "dispel_magic",
    "fear",
    "fireball",
    "fly",
    "gaseous_form",
    "glyph_of_warding",
    "haste",
    "hypnotic_pattern",
    "lightning_bolt",
    "magic_circle",
    "major_image",
    "nondetection",
    "phantom_steed",
    "protection_from_energy",
    "remove_curse",
    "sending",
    "sleet_storm",
    "slow",
    "stinking_cloud",
    "tiny_hut",
    "tongues",
    "vampiric_touch",
    "water_breathing",
    # 4th Level
    "arcane_eye",
    "banishment",
    "black_tentacles",
    "blight",
    "confusion",
    "conjure_minor_elementals",
    "control_water",
    "dimension_door",
    "fabricate",
    "faithful_hound",
    "fire_shield",
    "greater_invisibility",
    "hallucinatory_terrain",
    "ice_storm",
    "locate_creature",
    "phantasmal_killer",
    "polymorph",
    "private_sanctum",
    "resilient_sphere",
    "secret_chest",
    "stone_shape",
    "stoneskin",
    "wall_of_fire",
    # 5th Level
    "animate_objects",
    "arcane_hand",
    "cloudkill",
    "cone_of_cold",
    "conjure_elemental",
    "contact_other_plane",
    "creation",
    "dominate_person",
    "dream",
    "geas",
    "hold_monster",
    "legend_lore",
    "mislead",
    "modify_memory",
    "passwall",
    "planar_binding",
    "scrying",
    "seeming",
    "telekinesis",
    "telepathic_bond",
    "teleportation_circle",
    "wall_of_force",
    "wall_of_stone",
    # 6th Level
    "chain_lightning",
    "circle_of_death",
    "contingency",
    "create_undead",
    "disintegrate",
    "eyebite",
    "flesh_to_stone",
    "freezing_sphere",
    "globe_of_invulnerability",
    "guards_and_wards",
    "instant_summons",
    "irresistible_dance",
    "magic_jar",
    "mass_suggestion",
    "move_earth",
    "programmed_illusion",
    "sunbeam",
    "true_seeing",
    "wall_of_ice",
    # 7th Level
    "arcane_sword",
    "delayed_blast_fireball",
    "etherealness",
    "finger_of_death",
    "forcecage",
    "magnificent_mansion",
    "mirage_arcane",
    "plane_shift",
    "prismatic_spray",
    "project_image",
    "reverse_gravity",
    "sequester",
    "simulacrum",
    "symbol",
    "teleport",
    # 8th Level
    "antimagic_field",
    "antipathysympathy",
    "clone",
    "control_weather",
    "demiplane",
    "dominate_monster",
    "feeblemind",
    "incendiary_cloud",
    "maze",
    "mind_blank",
    "power_word_stun",
    "sunburst",
    # 9th Level
    "astral_projection",
    "foresight",
    "gate",
    "imprisonment",
    "meteor_swarm",
    "power_word_kill",
    "prismatic_wall",
    "shapechange",
    "time_stop",
    "true_polymorph",
    "weird",
    "wish",
]


# Mapping from simple_name to list of classes
def get_spell_classes(spell_simple_name: str) -> list[str]:
    """Return list of classes that can cast the given spell.

    Args:
        spell_simple_name: The simple_name of the spell (e.g., "fireball")

    Returns:
        Sorted list of class names (lowercase) that can cast this spell.
        Empty list if spell not found in any class list.
    """
    classes = []

    if spell_simple_name in BARD_SPELLS:
        classes.append("bard")
    if spell_simple_name in CLERIC_SPELLS:
        classes.append("cleric")
    if spell_simple_name in DRUID_SPELLS:
        classes.append("druid")
    if spell_simple_name in PALADIN_SPELLS:
        classes.append("paladin")
    if spell_simple_name in RANGER_SPELLS:
        classes.append("ranger")
    if spell_simple_name in SORCERER_SPELLS:
        classes.append("sorcerer")
    if spell_simple_name in WARLOCK_SPELLS:
        classes.append("warlock")
    if spell_simple_name in WIZARD_SPELLS:
        classes.append("wizard")

    return sorted(classes)
