"""Validation data for testing PDF extraction accuracy.

This module contains known-good reference data for class progression tables.
Used to validate that PDF extraction produces correct results.

ALL DATA MATCHES ACTUAL PDF EXTRACTION FORMAT:
- Levels are ordinal strings: "1st", "2nd", "3rd", etc.
- All numeric values are strings: "2", "3", "4", etc.
- Empty spell slots use " ̶" (space U+0020 + combining overline U+0336)
- Some classes use "—" (em-dash U+2014) or "̶" (overline alone)

This data was moved from src/srd_builder/table_extraction/reference_data.py
because it's only used for validation/testing, not by production extraction code.
"""

from typing import Any

VALIDATION_CLASS_PROGRESSIONS: dict[str, dict[str, Any]] = {
    "barbarian": {
        "headers": ["Level", "Proficiency Bonus", "Features", "Rages", "Rage Damage"],
        "rows": [
            ["1st", "+2", "Rage, Unarmored Defense", "2", "+2"],
            ["2nd", "+2", "Reckless Attack, Danger Sense", "2", "+2"],
            ["3rd", "+2", "Primal Path", "3", "+2"],
            ["4th", "+2", "Ability Score Improvement", "3", "+2"],
            ["5th", "+3", "Extra Attack, Fast Movement", "3", "+2"],
            ["6th", "+3", "Path feature", "4", "+2"],
            ["7th", "+3", "Feral Instinct", "4", "+2"],
            ["8th", "+3", "Ability Score Improvement", "4", "+2"],
            ["9th", "+4", "Brutal Critical (1 die)", "4", "+3"],
            ["10th", "+4", "Path feature", "4", "+3"],
            ["11th", "+4", "Relentless", "4", "+3"],
            ["12th", "+4", "Ability Score Improvement", "5", "+3"],
            ["13th", "+5", "Brutal Critical (2 dice)", "5", "+3"],
            ["14th", "+5", "Path feature", "5", "+3"],
            ["15th", "+5", "Persistent Rage", "5", "+3"],
            ["16th", "+5", "Ability Score Improvement", "5", "+4"],
            ["17th", "+6", "Brutal Critical (3 dice)", "6", "+4"],
            ["18th", "+6", "Indomitable Might", "6", "+4"],
            ["19th", "+6", "Ability Score Improvement", "6", "+4"],
            ["20th", "+6", "Primal Champion", "Unlimited", "+4"],
        ],
    },
    "bard": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Features",
            "Cantrips Known",
            "Spells Known",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "9th",
        ],
        "rows": [
            [
                "1st",
                "+2",
                "Spellcasting, Bardic Inspiration (d6)",
                "2",
                "4",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "2nd",
                "+2",
                "Jack of All Trades, Song of Rest (d6)",
                "2",
                "5",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "3rd",
                "+2",
                "Bard College, Expertise",
                "2",
                "6",
                "4",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "4th",
                "+2",
                "Ability Score Improvement",
                "3",
                "7",
                "4",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "5th",
                "+3",
                "Bardic Inspiration (d8), Font of Inspiration",
                "3",
                "8",
                "4",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "6th",
                "+3",
                "Countercharm, Bard College feature",
                "3",
                "9",
                "4",
                "3",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["7th", "+3", " ̶", "3", "10", "4", "3", "3", "1", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "8th",
                "+3",
                "Ability Score Improvement",
                "3",
                "11",
                "4",
                "3",
                "3",
                "2",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
            ],
            ["9th", "+4", "Song of Rest (d8)", "3", "12", "4", "3", "3", "3", "1", "̶", "̶", "̶", "̶"],
            [
                "10th",
                "+4",
                "Bardic Inspiration (d10), Expertise, Magical Secrets",
                "4",
                "14",
                "4",
                "3",
                "3",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["11th", "+4", " ̶", "4", "15", "4", "3", "3", "3", "2", "1", " ̶", " ̶", " ̶"],
            [
                "12th",
                "+4",
                "Ability Score Improvement",
                "4",
                "15",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "13th",
                "+5",
                "Song of Rest (d10)",
                "4",
                "16",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                " ̶",
                " ̶",
            ],
            [
                "14th",
                "+5",
                "Magical Secrets, Bard College feature",
                "4",
                "18",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                " ̶",
                " ̶",
            ],
            [
                "15th",
                "+5",
                "Bardic Inspiration (d12)",
                "4",
                "19",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                " ̶",
            ],
            [
                "16th",
                "+5",
                "Ability Score Improvement",
                "4",
                "19",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "̶",
            ],
            [
                "17th",
                "+6",
                "Song of Rest (d12)",
                "4",
                "20",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "18th",
                "+6",
                "Magical Secrets",
                "4",
                "22",
                "4",
                "3",
                "3",
                "3",
                "3",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "19th",
                "+6",
                "Ability Score Improvement",
                "4",
                "22",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
            ],
            [
                "20th",
                "+6",
                "Superior Inspiration",
                "4",
                "22",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "2",
                "1",
                "1",
            ],
        ],
    },
    "cleric": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Features",
            "Cantrips Known",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "9th",
        ],
        "rows": [
            [
                "1st",
                "+2",
                "Spellcasting, Divine Domain",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "2nd",
                "+2",
                "Channel Divinity (1/rest), Divine Domain feature",
                "3",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["3rd", "+2", " ̶", "3", "4", "2", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "4th",
                "+2",
                "Ability Score Improvement",
                "4",
                "4",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "5th",
                "+3",
                "Destroy Undead (CR 1/2)",
                "4",
                "4",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "6th",
                "+3",
                "Channel Divinity (2/rest), Divine Domain feature",
                "4",
                "4",
                "3",
                "3",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
            ],
            ["7th", "+3", " ̶", "4", "4", "3", "3", "1", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "8th",
                "+3",
                "Ability Score Improvement, Destroy Undead (CR 1), Divine Domain feature",
                "4",
                "4",
                "3",
                "3",
                "2",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
            ],
            ["9th", "+4", "̶", "4", "4", "3", "3", "3", "1", "̶", "̶", "̶", "̶"],
            ["10th", "+4", "Divine Intervention", "5", "4", "3", "3", "3", "2", "̶", "̶", "̶", "̶"],
            [
                "11th",
                "+4",
                "Destroy Undead (CR 2)",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "12th",
                "+4",
                "Ability Score Improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["13th", "+5", " ̶", "5", "4", "3", "3", "3", "2", "1", "1", " ̶", " ̶"],
            [
                "14th",
                "+5",
                "Destroy Undead (CR 3)",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                " ̶",
                " ̶",
            ],
            ["15th", "+5", "̶", "5", "4", "3", "3", "3", "2", "1", "1", "1", "̶"],
            [
                "16th",
                "+5",
                "Ability Score Improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "̶",
            ],
            [
                "17th",
                "+6",
                "Destroy Undead (CR 4), Divine Domain feature",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "18th",
                "+6",
                "Channel Divinity (3/rest)",
                "5",
                "4",
                "3",
                "3",
                "3",
                "3",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "19th",
                "+6",
                "Ability Score Improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
            ],
            [
                "20th",
                "+6",
                "Divine Intervention improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "2",
                "1",
                "1",
            ],
        ],
    },
    "druid": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Features",
            "Cantrips Known",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "9th",
        ],
        "rows": [
            [
                "1st",
                "+2",
                "Druidic, Spellcasting",
                "2",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "2nd",
                "+2",
                "Wild Shape, Druid Circle",
                "2",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["3rd", "+2", " ̶", "2", "4", "2", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "4th",
                "+2",
                "Wild Shape improvement, Ability Score Improvement",
                "3",
                "4",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["5th", "+3", " ̶", "3", "4", "3", "2", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            ["6th", "+3", "Druid Circle feature", "3", "4", "3", "3", "̶", "̶", "̶", "̶", "̶", "̶"],
            ["7th", "+3", "̶", "3", "4", "3", "3", "1", "̶", "̶", "̶", "̶", "̶"],
            [
                "8th",
                "+3",
                "Wild Shape improvement, Ability Score Improvement",
                "3",
                "4",
                "3",
                "3",
                "2",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
            ],
            ["9th", "+4", " ̶", "3", "4", "3", "3", "3", "1", " ̶", " ̶", " ̶", " ̶"],
            [
                "10th",
                "+4",
                "Druid Circle feature",
                "4",
                "4",
                "3",
                "3",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["11th", "+4", " ̶", "4", "4", "3", "3", "3", "2", "1", " ̶", " ̶", " ̶"],
            [
                "12th",
                "+4",
                "Ability Score Improvement",
                "4",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["13th", "+5", " ̶", "4", "4", "3", "3", "3", "2", "1", "1", " ̶", " ̶"],
            ["14th", "+5", "Druid Circle feature", "4", "4", "3", "3", "3", "2", "1", "1", "̶", "̶"],
            ["15th", "+5", "̶", "4", "4", "3", "3", "3", "2", "1", "1", "1", "̶"],
            [
                "16th",
                "+5",
                "Ability Score Improvement",
                "4",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "̶",
            ],
            ["17th", "+6", " ̶", "4", "4", "3", "3", "3", "2", "1", "1", "1", "1"],
            [
                "18th",
                "+6",
                "Timeless Body, Beast Spells",
                "4",
                "4",
                "3",
                "3",
                "3",
                "3",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "19th",
                "+6",
                "Ability Score Improvement",
                "4",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
            ],
            ["20th", "+6", "Archdruid", "4", "4", "3", "3", "3", "3", "2", "2", "1", "1"],
        ],
    },
    "fighter": {
        "headers": ["Level", "Proficiency Bonus", "Features"],
        "rows": [
            ["1st", "+2", "Fighting Style, Second Wind"],
            ["2nd", "+2", "Action Surge (one use)"],
            ["3rd", "+2", "Martial Archetype"],
            ["4th", "+2", "Ability Score Improvement"],
            ["5th", "+3", "Extra Attack"],
            ["6th", "+3", "Ability Score Improvement"],
            ["7th", "+3", "Martial Archetype feature"],
            ["8th", "+3", "Ability Score Improvement"],
            ["9th", "+4", "Indomitable (one use)"],
            ["10th", "+4", "Martial Archetype feature"],
            ["11th", "+4", "Extra Attack (2)"],
            ["12th", "+4", "Ability Score Improvement"],
            ["13th", "+5", "Indomitable (two uses)"],
            ["14th", "+5", "Ability Score Improvement"],
            ["15th", "+5", "Martial Archetype feature"],
            ["16th", "+5", "Ability Score Improvement"],
            ["17th", "+6", "Action Surge (two uses), Indomitable (three uses)"],
            ["18th", "+6", "Martial Archetype feature"],
            ["19th", "+6", "Ability Score Improvement"],
            ["20th", "+6", "Extra Attack (3)"],
        ],
    },
    "monk": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Martial Arts",
            "Ki Points",
            "Unarmored Movement",
            "Features",
        ],
        "rows": [
            ["1st", "+2", "1d4", "—", "—", "Unarmored Defense, Martial Arts"],
            ["2nd", "+2", "1d4", "2", "+10 ft.", "Ki, Unarmored Movement"],
            ["3rd", "+2", "1d4", "3", "+10 ft.", "Monastic Tradition, Deflect Missiles"],
            ["4th", "+2", "1d4", "4", "+10 ft.", "Ability Score Improvement, Slow Fall"],
            ["5th", "+3", "1d6", "5", "+10 ft.", "Extra Attack, Stunning Strike"],
            [
                "6th",
                "+3",
                "1d6",
                "6",
                "+15 ft.",
                "Ki-\xad‐Empowered Strikes, Monastic Tradition feature",
            ],
            ["7th", "+3", "1d6", "7", "+15 ft.", "Evasion, Stillness of Mind"],
            ["8th", "+3", "1d6", "8", "+15 ft.", "Ability Score Improvement"],
            ["9th", "+4", "1d6", "9", "+15 ft.", "Unarmored Movement improvement"],
            ["10th", "+4", "1d6", "10", "+20 ft.", "Purity of Body"],
            ["11th", "+4", "1d8", "11", "+20 ft.", "Monastic Tradition feature"],
            ["12th", "+4", "1d8", "12", "+20 ft.", "Ability Score Improvement"],
            ["13th", "+5", "1d8", "13", "+20 ft.", "Tongue of the Sun and Moon"],
            ["14th", "+5", "1d8", "14", "+25 ft.", "Diamond Soul"],
            ["15th", "+5", "1d8", "15", "+25 ft.", "Timeless Body"],
            ["16th", "+5", "1d8", "16", "+25 ft.", "Ability Score Improvement"],
            ["17th", "+6", "1d10", "17", "+25 ft.", "Monastic Tradition feature"],
            ["18th", "+6", "1d10", "18", "+30 ft.", "Empty Body"],
            ["19th", "+6", "1d10", "19", "+30 ft.", "Ability Score Improvement"],
            ["20th", "+6", "1d10", "20", "+30 ft.", "Perfect Self"],
        ],
    },
    "paladin": {
        "headers": ["Level", "Proficiency Bonus", "Features", "1st", "2nd", "3rd", "4th", "5th"],
        "rows": [
            ["1st", "+2", "Divine Sense, Lay on Hands", "̶", "̶", "̶", "̶", "̶"],
            ["2nd", "+2", "Fighting Style, Spellcasting,", "Divine Smite 2", " ̶", " ̶", " ̶", " ̶"],
            ["3rd", "+2", "Divine Health, Sacred Oath", "3", " ̶", " ̶", " ̶", " ̶"],
            ["4th", "+2", "Ability Score Improvement", "3", " ̶", " ̶", " ̶", " ̶"],
            ["5th", "+3", "Extra Attack", "4", "2", " ̶", " ̶", " ̶"],
            ["6th", "+3", "Aura of Protection", "4", "2", " ̶", " ̶", " ̶"],
            ["7th", "+3", "Sacred Oath feature", "4", "3", "̶", "̶", "̶"],
            ["8th", "+3", "Ability Score Improvement", "4", "3", "̶", "̶", "̶"],
            ["9th", "+4", " ̶", "4", "3", "2", " ̶", " ̶"],
            ["10th", "+4", "Aura of Courage", "4", "3", "2", " ̶", " ̶"],
            ["11th", "+4", "Improved Divine Smite", "4", "3", "3", " ̶", " ̶"],
            ["12th", "+4", "Ability Score Improvement", "4", "3", "3", " ̶", " ̶"],
            ["13th", "+5", "̶", "4", "3", "3", "1", "̶"],
            ["14th", "+5", "Cleansing Touch", "4", "3", "3", "1", "̶"],
            ["15th", "+5", "Sacred Oath feature", "4", "3", "3", "2", " ̶"],
            ["16th", "+5", "Ability Score Improvement", "4", "3", "3", "2", " ̶"],
            ["17th", "+6", " ̶", "4", "3", "3", "3", "1"],
            ["18th", "+6", "Aura improvements", "4", "3", "3", "3", "1"],
            ["19th", "+6", "Ability Score Improvement", "4", "3", "3", "3", "2"],
            ["20th", "+6", "Sacred Oath feature", "4", "3", "3", "3", "2"],
        ],
    },
    "ranger": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Features",
            "Spells Known",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
        ],
        "rows": [
            ["1st", "+2", "Favored Enemy, Natural Explorer", " ̶", "", " ̶", " ̶", " ̶", " ̶"],
            ["2nd", "+2", "Fighting Style, Spellcasting", "", "2", "2", " ̶", " ̶", " ̶"],
            ["3rd", "+2", "Ranger Archetype, Primeval Awareness", "", "3", "3", " ̶", " ̶", " ̶"],
            ["4th", "+2", "Ability Score Improvement", "", "3", "3", " ̶", " ̶", " ̶"],
            ["5th", "+3", "Extra Attack", "", "4", "4", "2", " ̶", " ̶"],
            [
                "6th",
                "+3",
                "Favored Enemy and Natural Explorer",
                "improvements",
                "4",
                "4",
                "2",
                "̶",
                "̶",
            ],
            ["7th", "+3", "Ranger Archetype feature", "", "5", "4", "3", "̶", "̶"],
            ["8th", "+3", " Ability Score Improvement, Land’s", " Stride", "5", "4", "3", " ̶", " ̶"],
            ["9th", "+4", " ̶", "", "6", "4", "3", "2", " ̶"],
            [
                "10th",
                "+4",
                "Natural Explorer improvement,",
                "Hide in Plain Sight",
                "6",
                "4",
                "3",
                "2",
                " ̶",
            ],
            ["11th", "+4", "Ranger Archetype feature", "", "7", "4", "3", "3", " ̶"],
            ["12th", "+4", "Ability Score Improvement", "", "7", "4", "3", "3", "̶"],
            ["13th", "+5", "̶", "", "8", "4", "3", "3", "1"],
            ["14th", "+5", "Favored Enemy improvement, Vanish", "", "8", "4", "3", "3", "1"],
            ["15th", "+5", "Ranger Archetype feature", "", "9", "4", "3", "3", "2"],
            ["16th", "+5", "Ability Score Improvement", "", "9", "4", "3", "3", "2"],
            ["17th", "+6", " ̶", "10", "", "4", "3", "3", "3"],
            ["18th", "+6", "Feral Senses", "10", "", "4", "3", "3", "3"],
            ["19th", "+6", "Ability Score Improvement", "11", "", "4", "3", "3", "3"],
            ["20th", "+6", "Foe Slayer", "11", "", "4", "3", "3", "3"],
        ],
    },
    "rogue": {
        "headers": ["Level", "Proficiency Bonus", "Sneak Attack", "Features"],
        "rows": [
            ["1st", "+2", "1d6", "Expertise, Sneak Attack, Thieves’ Cant"],
            ["2nd", "+2", "1d6", "Cunning Action"],
            ["3rd", "+2", "2d6", "Roguish Archetype"],
            ["4th", "+2", "2d6", "Ability Score Improvement"],
            ["5th", "+3", "3d6", "Uncanny Dodge"],
            ["6th", "+3", "3d6", "Expertise"],
            ["7th", "+3", "4d6", "Evasion"],
            ["8th", "+3", "4d6", "Ability Score Improvement"],
            ["9th", "+4", "5d6", "Roguish Archetype feature"],
            ["10th", "+4", "5d6", "Ability Score"],
            ["11th", "+4", "6d6", "Reliable Talent"],
            ["12th", "+4", "6d6", "Ability Score Improvement"],
            ["13th", "+5", "7d6", "Roguish Archetype feature"],
            ["14th", "+5", "7d6", "Blindsense"],
            ["15th", "+5", "8d6", "Slippery Mind"],
            ["16th", "+5", "8d6", "Ability Score Improvement"],
            ["17th", "+6", "9d6", "Roguish Archetype feature"],
            ["18th", "+6", "9d6", "Elusive"],
            ["19th", "+6", "10d6", "Ability Score Improvement"],
            ["20th", "+6", "10d6", "Stroke of Luck"],
        ],
    },
    "sorcerer": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Sorcery Points",
            "Features",
            "Cantrips Known",
            "Spells Known",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "9th",
        ],
        "rows": [
            [
                "1st",
                "+2",
                " ̶",
                "Spellcasting, Sorcerous Origin",
                "4",
                "2",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            [
                "2nd",
                "+2",
                "2",
                "Font of Magic",
                "4",
                "3",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["3rd", "+2", "3", "Metamagic", "4", "4", "4", "2", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "4th",
                "+2",
                "4",
                "Ability Score Improvement",
                "5",
                "5",
                "4",
                "3",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["5th", "+3", "5", " ̶", "5", "6", "4", "3", "2", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "6th",
                "+3",
                "6",
                "Sorcerous Origin feature",
                "5",
                "7",
                "4",
                "3",
                "3",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
            ],
            ["7th", "+3", "7", "̶", "5", "8", "4", "3", "3", "1", "̶", "̶", "̶", "̶", "̶"],
            [
                "8th",
                "+3",
                "8",
                "Ability Score Improvement",
                "5",
                "9",
                "4",
                "3",
                "3",
                "2",
                "̶",
                "̶",
                "̶",
                "̶",
                "̶",
            ],
            ["9th", "+4", "9", "̶", "5", "10", "4", "3", "3", "3", "1", "̶", "̶", "̶", "̶"],
            [
                "10th",
                "+4",
                "10",
                "Metamagic",
                "6",
                "11",
                "4",
                "3",
                "3",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["11th", "+4", "11", " ̶", "6", "12", "4", "3", "3", "3", "2", "1", " ̶", " ̶", " ̶"],
            [
                "12th",
                "+4",
                "12",
                "Ability Score Improvement",
                "6",
                "12",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["13th", "+5", "13", " ̶", "6", "13", "4", "3", "3", "3", "2", "1", "1", " ̶", " ̶"],
            [
                "14th",
                "+5",
                "14",
                "Sorcerous Origin feature",
                "6",
                "13",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                " ̶",
                " ̶",
            ],
            ["15th", "+5", "15", " ̶", "6", "14", "4", "3", "3", "3", "2", "1", "1", "1", " ̶"],
            [
                "16th",
                "+5",
                "16",
                "Ability Score Improvement",
                "6",
                "14",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "̶",
            ],
            [
                "17th",
                "+6",
                "17",
                "Metamagic",
                "6",
                "15",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "18th",
                "+6",
                "18",
                "Sorcerous Origin feature",
                "6",
                "15",
                "4",
                "3",
                "3",
                "3",
                "3",
                "1",
                "1",
                "1",
                "1",
            ],
            [
                "19th",
                "+6",
                "19",
                "Ability Score Improvement",
                "6",
                "15",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
            ],
            [
                "20th",
                "+6",
                "20",
                "Sorcerous Restoration",
                "6",
                "15",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "2",
                "1",
                "1",
            ],
        ],
    },
    "warlock": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Features",
            "Cantrips Known",
            "Invocations Known",
            "Spell Slots",
            "Slot Level",
        ],
        "rows": [
            ["1st", "+2", "Otherworldly Patron, Pact Magic", "2", "2", "1", "1st"],
            ["2nd", "+2", "Eldritch Invocations", "2", "3", "2", "1st"],
            ["3rd", "+2", "Pact Boon", "2", "4", "2", "2nd"],
            ["4th", "+2", "Ability Score Improvement", "3", "5", "2", "2nd"],
            ["5th", "+3", " ̶", "3", "6", "2", "3rd"],
            ["6th", "+3", "Otherworldly Patron feature", "3", "7", "2", "3rd"],
            ["7th", "+3", " ̶", "3", "8", "2", "4th"],
            ["8th", "+3", "Ability Score Improvement", "3", "9", "2", "4th"],
            ["9th", "+4", "̶", "3", "10", "2", "5th"],
            ["10th", "+4", "Otherworldly Patron feature", "4", "10", "2", "5th"],
            ["11th", "+4", "Mystic Arcanum (6th level)", "4", "11", "3", "5th"],
            ["12th", "+4", "Ability Score Improvement", "4", "11", "3", "5th"],
            ["13th", "+5", "Mystic Arcanum (7th level)", "4", "12", "3", "5th"],
            ["14th", "+5", "Otherworldly Patron feature", "4", "12", "3", "5th"],
            ["15th", "+5", "Mystic Arcanum (8th level)", "4", "13", "3", "5th"],
            ["16th", "+5", "Ability Score Improvement", "4", "13", "3", "5th"],
            ["17th", "+6", "Mystic Arcanum (9th level)", "4", "14", "4", "5th"],
            ["18th", "+6", "̶", "4", "14", "4", "5th"],
            ["19th", "+6", "Ability Score Improvement", "4", "15", "4", "5th"],
            ["20th", "+6", "Eldritch Master", "4", "15", "4", "5th"],
        ],
    },
    "wizard": {
        "headers": [
            "Level",
            "Proficiency Bonus",
            "Features",
            "Cantrips Known",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "9th",
        ],
        "rows": [
            [
                "1st",
                "+2",
                "Spellcasting, Arcane Recovery",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["2nd", "+2", "Arcane Tradition", "3", "3", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            ["3rd", "+2", " ̶", "3", "4", "2", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶", " ̶"],
            ["4th", "+2", "Ability Score Improvement", "4", "4", "3", "̶", "̶", "̶", "̶", "̶", "̶", "̶"],
            ["5th", "+3", "̶", "4", "4", "3", "2", "̶", "̶", "̶", "̶", "̶", "̶"],
            ["6th", "+3", "Arcane Tradition feature", "4", "4", "3", "3", "̶", "̶", "̶", "̶", "̶", "̶"],
            ["7th", "+3", " ̶", "4", "4", "3", "3", "1", " ̶", " ̶", " ̶", " ̶", " ̶"],
            [
                "8th",
                "+3",
                "Ability Score Improvement",
                "4",
                "4",
                "3",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["9th", "+4", " ̶", "4", "4", "3", "3", "3", "1", " ̶", " ̶", " ̶", " ̶"],
            [
                "10th",
                "+4",
                "Arcane Tradition feature",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                " ̶",
                " ̶",
                " ̶",
                " ̶",
            ],
            ["11th", "+4", "̶", "5", "4", "3", "3", "3", "2", "1", "̶", "̶", "̶"],
            [
                "12th",
                "+4",
                "Ability Score Improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "̶",
                "̶",
                "̶",
            ],
            ["13th", "+5", " ̶", "5", "4", "3", "3", "3", "2", "1", "1", " ̶", " ̶"],
            [
                "14th",
                "+5",
                "Arcane Tradition feature",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                " ̶",
                " ̶",
            ],
            ["15th", "+5", " ̶", "5", "4", "3", "3", "3", "2", "1", "1", "1", " ̶"],
            [
                "16th",
                "+5",
                "Ability Score Improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
                " ̶",
            ],
            ["17th", "+6", " ̶", "5", "4", "3", "3", "3", "2", "1", "1", "1", "1"],
            ["18th", "+6", "Spell Mastery", "5", "4", "3", "3", "3", "3", "1", "1", "1", "1"],
            [
                "19th",
                "+6",
                "Ability Score Improvement",
                "5",
                "4",
                "3",
                "3",
                "3",
                "3",
                "2",
                "1",
                "1",
                "1",
            ],
            ["20th", "+6", "Signature Spell", "5", "4", "3", "3", "3", "3", "2", "2", "1", "1"],
        ],
    },
}


def get_validation_data(simple_name: str) -> dict[str, Any] | None:
    """Get validation data for a table by simple_name.

    Args:
        simple_name: The simple_name of the table (e.g., "barbarian_progression")

    Returns:
        The validation data dict with "headers" and "rows", or None if not found
    """
    if not simple_name.endswith("_progression"):
        return None
    class_name = simple_name.replace("_progression", "")
    return VALIDATION_CLASS_PROGRESSIONS.get(class_name)
