"""Calculated pattern: rows generated by formula or lookup config."""

from __future__ import annotations

import logging
from typing import Any

from ._types import RawTable

logger = logging.getLogger(__name__)


def _extract_calculated(
    table_id: str,
    simple_name: str,
    page: int | list[int],
    config: dict[str, Any],
    section: str | None,
) -> RawTable:
    """Extract calculated table (formula or lookup based).

    Config structure:
        {
            "pattern_type": "calculated",
            "source": "derived" | "convenience",
            "calculation": {
                "method": "formula" | "lookup",
                "formula": lambda x: ...,  # if method=formula
                "data": {...},              # if method=lookup
                "range": range(...),
            },
            "headers": [...],
            "notes": "..."
        }
    """
    calc_config = config["calculation"]
    method = calc_config["method"]

    if method == "formula":
        rows = _generate_formula_rows(calc_config)
    elif method == "lookup":
        rows = _generate_lookup_rows(calc_config)
    else:
        raise ValueError(f"Unknown calculation method '{method}' for {simple_name}")

    source = config.get("source", "calculated")
    notes = config.get("notes", f"Calculated table [source: {source}]")
    chapter = config.get("chapter")
    confirmed = config.get("confirmed", False)

    return RawTable(
        table_id=table_id,
        simple_name=simple_name,
        page=page,
        headers=config["headers"],
        rows=rows,
        extraction_method="calculated",
        section=section,
        notes=notes,
        chapter=chapter,
        confirmed=confirmed,
        source=source,
    )


def _build_category_metadata(
    rows: list[list[str | int | float]], headers: list[str]
) -> dict[str, Any]:
    """Build category metadata from extracted rows.

    Categories are detected when all numeric columns contain only "—" (em-dash).
    The first column contains the category name.

    Returns:
        Dict with "categories" key mapping category names to item lists:
        {
            "categories": {
                "Category Name": {
                    "row_index": 0,
                    "items": [{"name": "Item1", "row_index": 1}, ...]
                }
            }
        }
    """
    categories: dict[str, dict[str, Any]] = {}
    current_category: str | None = None

    for i, row in enumerate(rows):
        # Category detection: all columns except first are "—" or empty
        is_category = all(str(cell).strip() in ("—", "") for cell in row[1:])

        if is_category and row[0]:
            # This is a category header
            category_name = str(row[0]).strip()
            current_category = category_name
            categories[current_category] = {"row_index": i, "items": []}
        elif current_category and row[0]:
            # This is an item under the current category
            item_name = str(row[0]).strip()
            categories[current_category]["items"].append({"name": item_name, "row_index": i})

    return {"categories": categories} if categories else {}


def _generate_formula_rows(config: dict[str, Any]) -> list[list[str | int | float]]:
    """Generate rows from formula config.

    Example config:
        {
            "formula": lambda x: x * 15,
            "range": range(1, 31),
            "headers": ["Strength", "Capacity"],
            "format": lambda val: f"{val} lbs"  # optional
        }
    """
    formula = config["formula"]
    value_range = config["range"]
    format_fn = config.get("format_modifier") or config.get("format", lambda x: x)

    rows: list[list[str | int | float]] = []
    for val in value_range:
        result = formula(val)
        formatted_result = format_fn(result)
        rows.append([val, formatted_result])

    return rows


def _generate_lookup_rows(config: dict[str, Any]) -> list[list[str | int | float]]:
    """Generate rows from lookup dict config.

    Example config:
        {
            "data": {
                range(1, 5): "+2",
                range(5, 9): "+3",
                ...
            },
            "headers": ["Level", "Bonus"]
        }
    """
    lookup = config["data"]
    rows: list[list[str | int | float]] = []

    # Build lookup by iterating ranges
    for range_obj, value in lookup.items():
        for key in range_obj:
            rows.append([key, value])

    return rows
