name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Guard — forbid SRD PDFs/TXT
        run: |
          set -e
          if git ls-files | grep -E 'rulesets/.+\.(pdf|docx|txt)$'; then
            echo "::error::Found SRD source documents committed under rulesets/. Remove them."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Import order (isort)
        run: isort --check-only .

      - name: Type check (mypy)
        run: mypy src
        continue-on-error: true

      - name: Tests (pytest)
        run: pytest -q
